INSERT INTO category (name) VALUES ('Programador');
INSERT INTO category (name) VALUES ('Comerciante');
INSERT INTO client (name, age, vat_number, email, id_category) VALUES ('Guido Imbens', 21, '12354236123', 'imbens@gmail.com', 1);
INSERT INTO client (name, age, vat_number, email, id_category) VALUES ('Joshua Angrist', 65, '12354236123', 'angrist@hotmail.com', 1);
INSERT INTO client (name, age, vat_number, email, id_category) VALUES ('Paul Milgrom', 23, '12354236123', 'milgrom@outlook.com', 1);
INSERT INTO client (name, age, vat_number, email, id_category) VALUES ('Abhijit Banerjee', 56, '12354236123', 'banerjee@yahoo.com', 1);
INSERT INTO client (name, age, vat_number, email, id_category) VALUES ('Paul Romer', 35, '12354236123', 'romer@ig.com', 2);
INSERT INTO client (name, age, vat_number, email, id_category) VALUES ('David Card', 24, '12354236123', 'card@aol.com', 2);
INSERT INTO client (name, age, vat_number, email, id_category) VALUES ('Robert B. Wilson', 56, '12354236123', 'wilson@ibest.com.br', 2);
INSERT INTO client (name, age, vat_number, email, id_category) VALUES ('Michael Kremer', 68, '12354236123', 'kremer@godaddy.com', 2);
INSERT INTO client (name, age, vat_number, email, id_category) VALUES ('Esther Duflo', 45, '12354236123', 'duflo@uol.com.br', 2);
